# Generated by Django 6.0.3 on 2026-03-12 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_backfill_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='task',
            name='tag_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
